version: "3.2"
services:
  ansible:
    image: jeromeklam/u20_ansible
    networks:
      - frontend
      - backend
    volumes:
      - ./:/etc/ansible
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  frontend:
  backend: